=== domstolene/esas-kontrakt/kontrakter/kjennelseBeslutning/kjennelseBeslutning/kjennelseBeslutning.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://domstol.no/kjennelseBeslutning/1.1/kjennelseBeslutning",
  "description": "Skjema som definerer en generell kjennelse eller beslutning",
  "properties": {
    "pakkeId": {
      "$ref": "#/definitions/GUID",
      "description": "Hvis meldingen sendes sammen med flere meldinger så vil alle meldingene ha samme pakke-id."
    },
    "forsendelse": {
      "$ref": "#/definitions/forsendelse",
      "description": "Avsender og mottaker"
    },
    "aktoerer": {
      "description": "Aktører fra domstolen",
      "properties": {
        "dommer": {
          "$ref": "#/definitions/ansattPerson",
          "description": "Dommer på saken"
        },
        "saksbehandler": {
          "$ref": "#/definitions/ansattPerson",
          "description": "Saksbehandler på saken"
        }
      },
      "required": ["dommer", "saksbehandler"],
      "type": "object",
      "additionalProperties": false
    },
    "dokumenter": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/dokument"
      },
      "minItems": 0
    },
    "saksInformasjon": {
      "$ref": "#/definitions/saksInformasjon"
    }
  },
  "required": [
    "pakkeId",
    "forsendelse",
    "aktoerer",
    "dokumenter",
    "saksInformasjon"
  ],
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "saksInformasjon": {
      "properties": {
        "saksnummer": {
          "type": "string",
          "description": "Domstolen sitt interne saksnummer"
        },
        "straffesaksnummer": {
          "$ref": "#/definitions/straffesaksnummer",
          "description": "Politiet sitt interne hovedstraffesaksnummer"
        },
        "avgjoerelse": {
          "$ref": "#/definitions/avgjoerelse"
        }
      },
      "required": ["saksnummer", "straffesaksnummer", "avgjoerelse"],
      "type": "object",
      "additionalProperties": false
    },
    "avgjoerelse": {
      "properties": {
        "avgjoerelseId": {
          "$ref": "#/definitions/GUID",
          "description": "Domstolen sin id for avgjørelsen. Kan bli brukt i forbindelse med anke/forlengelse. AvgjørelseId beholdes ved korrigeringer"
        },
        "avgjoerelseIdForrigeInstans": {
          "$ref": "#/definitions/GUID",
          "description": "Domstolen sin id til avgjørelsen i forrige instans. Settes kun dersom dette er en avgjørelse i en ankesak"
        },
        "avsagtDato": {
          "$ref": "#/definitions/dato"
        },
        "kravId": {
          "$ref": "#/definitions/GUID",
          "description": "KravId i nåværende instans. Kan være null dersom saken er opprettet manuelt"
        },
        "opprinneligKravId": {
          "$ref": "#/definitions/GUID",
          "description": "KravId i første instans."
        },
        "avgjoerelsePrPerson": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/personForetakAvgjoerelse"
          },
          "minItems": 1
        }
      },
      "required": ["avgjoerelseId", "avsagtDato", "avgjoerelsePrPerson"],
      "type": "object",
      "additionalProperties": false
    },
    "personForetakAvgjoerelse": {
      "properties": {
        "personForetak": {
          "$ref": "#/definitions/personForetak"
        },
        "kategori": {
          "$ref": "#/definitions/avgjoerelseKategori",
          "description": "Kategori for avgjørelsen"
        },
        "beskrivelse": {
          "type": "string",
          "description": "Fritekst som beskriver avgjørelsen."
        },
        "typeAvgjoerelse": {
          "$ref": "#/definitions/avgjoerelseType",
          "description": "Hva slags type avgjørelse dette er"
        },
        "reaksjoner": {
          "$ref": "#/definitions/reaksjonsType",
          "description": "Kombinasjon av reaksjoner for denne personen. Dersom saken trekkes eller lukkes blir ikke dette elementet med."
        },
        "erklaering": {
          "properties": {
            "erklaeringSiktede": {
              "$ref": "#/definitions/erklaeringsDetaljer"
            },
            "erklaeringPaatale": {
              "$ref": "#/definitions/erklaeringsDetaljer"
            }
          },
          "required": ["erklaeringSiktede", "erklaeringPaatale"],
          "type": "object",
          "additionalProperties": false
        }
      },
      "required": ["personForetak", "kategori", "typeAvgjoerelse"],
      "type": "object",
      "additionalProperties": false
    },
    "forsendelse": {
      "properties": {
        "meldingsId": {
          "$ref": "#/definitions/GUID"
        },
        "sendtTid": {
          "type": "string",
          "format": "date-time"
        },
        "avsender": {
          "$ref": "#/definitions/avsender"
        },
        "mottaker": {
          "$ref": "#/definitions/mottaker"
        }
      },
      "required": ["meldingsId", "sendtTid", "avsender", "mottaker"],
      "type": "object",
      "additionalProperties": false
    },
    "avsender": {
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        },
        "person": {
          "description": "Person som sender meldingen. Vanligvis dommeren eller saksbehandleren",
          "$ref": "#/definitions/ansattPerson"
        }
      },
      "required": ["organisasjon"],
      "type": "object",
      "additionalProperties": false
    },
    "mottaker": {
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        }
      },
      "required": ["organisasjon"],
      "type": "object",
      "additionalProperties": false
    },
    "organisasjon": {
      "description": "Entydig identifikator av juridisk enhet. F.eks et spesifikt domstol embete eller politidistrikt",
      "properties": {
        "navn": {
          "type": "string",
          "description": "F.eks. Nordland politidistrikt eller Oslo tingrett."
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        }
      },
      "required": ["organisasjonsnummer"],
      "type": "object",
      "additionalProperties": false
    },
    "dokument": {
      "description": "Et dokument har en ID for at det skal kunne refereres til fra andre steder.",
      "properties": {
        "internId": {
          "description": "Referanse/journal nummer fra BL, Lovisa eller KODA/Kompis",
          "type": "string",
          "minLength": 2,
          "maxLength": 50
        },
        "forsendelse": {
          "$ref": "#/definitions/dokumentforsendelse"
        },
        "overskrift": {
          "description": "Klippe på slutten hvis det er for langt",
          "type": "string",
          "minLength": 2,
          "maxLength": 260
        },
        "skrevetDato": {
          "$ref": "#/definitions/dato"
        },
        "kategori": {
          "$ref": "#/definitions/kodeverk"
        }
      },
      "required": ["internId", "forsendelse", "overskrift", "kategori"],
      "type": "object",
      "additionalProperties": false
    },
    "dokumentforsendelse": {
      "description": "Detaljer om lokasjon og type",
      "properties": {
        "mimeType": {
          "type": "string"
        },
        "sjekksum": {
          "type": "string",
          "description": "Sjekksum av dokumentet basert på md5sum algoritmen."
        },
        "uri": {
          "type": "string"
        }
      },
      "required": ["mimeType", "sjekksum", "uri"],
      "type": "object",
      "additionalProperties": false
    },
    "ansattPerson": {
      "description": "Type for personer som er ansatt hos påtale eller domstolen(saksbehandlere, påtaleadvokater, statsadvokater,...)",
      "properties": {
        "etternavn": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "tittel": {
          "type": "string"
        }
      },
      "required": ["etternavn", "fornavn", "tittel"],
      "type": "object",
      "additionalProperties": false
    },
    "personForetak": {
      "type": "object",
      "description": "Person i personliste eller et foretak i foretaklisten",
      "properties": {
        "person": {
          "$ref": "#/definitions/siktetPerson"
        },
        "foretak": {
          "$ref": "#/definitions/foretak"
        }
      },
      "oneOf": [
        {
          "properties": {
            "person": {
              "$ref": "#/definitions/siktetPerson"
            }
          },
          "additionalProperties": false,
          "type": "object",
          "required": ["person"]
        },
        {
          "properties": {
            "foretak": {
              "$ref": "#/definitions/foretak"
            }
          },
          "additionalProperties": false,
          "type": "object",
          "required": ["foretak"]
        }
      ]
    },
    "siktetPerson": {
      "description": "Person som har en rolle i en straffesak (siktet, mistenkt, osv) der det er krav om fødselsnummer for nordmenn. Andre identifikatorer kan være interne, DUF nummer, pass nummer ...",
      "properties": {
        "internId": {
          "$ref": "#/definitions/internId",
          "description": "Intern id i melding, samme person i denne meldingen vil ha samme internId"
        },
        "etternavn": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "identitetsnummer": {
          "$ref": "#/definitions/personIdentifikator",
          "description": "Fødselsnummer, D-nummer eller SSP nummer. Alle personer som det er foretatt tvangsmidler mot skal ha et D-nummer eller fødselsnummer. Dersom politiet ikke har et slikt nummer vil de generere ett 'SSP nummer'"
        },
        "tilleggsId": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/personIdentifikator"
          },
          "description": "Kan f.eks. være historiske SSP nummer. "
        },
        "foedselsdato": {
          "$ref": "#/definitions/dato",
          "description": "Påbudt i BL i dag, men er ikke sikkert politiet vet."
        },
        "kjoenn": {
          "$ref": "#/definitions/kjoenn"
        },
        "statsborgerskap": {
          "description": "Tom array dersom statsborgerskap er ukjennt",
          "type": "array",
          "items": {
            "$ref": "#/definitions/land"
          }
        },
        "oppnevntForsvarer": {
          "$ref": "#/definitions/profesjonellPerson",
          "description": "Informasjon om oppnevnt forsvarer."
        }
      },
      "required": [
        "internId",
        "etternavn",
        "identitetsnummer",
        "tilleggsId",
        "statsborgerskap"
      ],
      "type": "object",
      "additionalProperties": false
    },
    "profesjonellPerson": {
      "type": "object",
      "description": " Typisk advokat.",
      "properties": {
        "tittel": {
          "type": "string"
        },
        "etternavn": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "identitetsnummer": {
          "$ref": "#/definitions/personIdentifikator",
          "description": "Fødsels- eller D-nummer"
        },
        "kontakt": {
          "$ref": "#/definitions/kontaktInfoPerson"
        },
        "praksis": {
          "$ref": "#/definitions/organisasjon",
          "description": "Personens praksiss i denne saken"
        }
      },
      "required": ["etternavn"],
      "additionalProperties": false
    },
    "foretak": {
      "description": "Foretak/ organisasjon som er med i en straffesak som f.eks. siktet",
      "properties": {
        "internId": {
          "$ref": "#/definitions/internId",
          "description": "Unik id lokalt i meldingen, samme internId er samme foretak."
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        },
        "navn": {
          "type": "string"
        }
      },
      "required": ["internId", "navn"],
      "type": "object",
      "additionalProperties": false
    },
    "reaksjonsType": {
      "properties": {
        "tapAvFoererett": {
          "description": "Midlertidig tap av førerett",
          "$ref": "#/definitions/tapAvFoererett"
        },
        "annet": {
          "$ref": "#/definitions/annet"
        }
      },
      "type": "object",
      "additionalProperties": false
    },
    "tapAvFoererett": {
      "properties": {
        "varighet": {
          "$ref": "#/definitions/lengde",
          "description": "Lengden på tapet av føreretten"
        },
        "dato": {
          "$ref": "#/definitions/dato",
          "description": "Tap av førerett inntil denne datoen"
        }
      },
      "oneOf": [
        {
          "properties": {
            "varighet": {
              "$ref": "#/definitions/lengde"
            }
          },
          "required": ["varighet"],
          "additionalProperties": false
        },
        {
          "properties": {
            "dato": {
              "$ref": "#/definitions/dato"
            }
          },
          "required": ["dato"],
          "additionalProperties": false
        }
      ],
      "type": "object",
      "additionalProperties": false
    },
    "annet": {
      "properties": {
        "tekst": {
          "type": "string",
          "description": "Fritekst som beskriver 'annet'-reaksjonen"
        }
      },
      "required": ["tekst"],
      "type": "object",
      "additionalProperties": false
    },
    "erklaeringsDetaljer": {
      "properties": {
        "meddeltIRettsmoete": {
          "type": "boolean",
          "description": "Settes til true dersom avgjørelsen er meddelt i rettsmøtet"
        },
        "meddeltDato": {
          "$ref": "#/definitions/dato",
          "description": "Dato for når avgjørelsen ble meddelt"
        },
        "erklaert": {
          "$ref": "#/definitions/erklaertType",
          "description": "Settes dersom avgjørelsen er meddelt i retten"
        },
        "ankeDetaljer": {
          "$ref": "#/definitions/ankeDetaljer",
          "description": "Settes dersom parten har anket hele eller deler av avgjørelsen"
        }
      },
      "required": ["meddeltIRettsmoete"],
      "type": "object",
      "additionalProperties": false
    },
    "ankeDetaljer": {
      "properties": {
        "anketDato": {
          "$ref": "#/definitions/dato"
        },
        "oppsettendeVirkning": {
          "type": "boolean",
          "description": "Settes om det ønskes oppsettende virkning"
        },
        "ankeBeskrivelse": {
          "type": "string",
          "description": "Kan brukes for å utdype hva som er anket."
        }
      },
      "required": ["anketDato"],
      "type": "object",
      "additionalProperties": false
    },
    "erklaertType": {
      "enum": ["VEDTATT", "ANKET", "BETENKNINGSTID"]
    },
    "avgjoerelseKategori": {
      "description": "Ved 'REAKSJON' skal minst en 'reaksjonsType' være utfylt. 'SAKEN_AVVIST' brukes ved trukket tilståelse. 'SAK_AVVISET_ANNET' dersom sak lukkes uten avgjørelse. 'ANNET' på andre ting",
      "enum": [
        "REAKSJON",
        "FRIFUNNET",
        "SAKEN_AVVIST",
        "SAK_AVVIST_ANNET",
        "ANNET"
      ],
      "type": "string"
    },
    "avgjoerelseType": {
      "description": "Type avgjørelse. Kjennelse eller beslutning, og om beslutningen kan ankes eller ikke",
      "enum": ["KJENNELSE", "BESLUTNING_INGEN_ANKE", "BESLUTNING_KAN_ANKES"],
      "type": "string"
    },
    "kontaktInfoPerson": {
      "type": "object",
      "description": "Epost og/eller telefonnummer/mobil om tilgjengelig",
      "properties": {
        "epost": {
          "$ref": "#/definitions/epost"
        },
        "telefonnummer": {
          "$ref": "#/definitions/telefonnummer"
        }
      },
      "additionalProperties": false
    },
    "land": {
      "description": "En landkode består av tre store bokstaver fra kodelisten ISO 3166-1-alpha-3. Hentes fra kodeverk nationality.xml",
      "type": "object",
      "properties": {
        "kode": {
          "type": "string",
          "pattern": "^[A-Z]+$",
          "minLength": 3,
          "maxLength": 3
        },
        "navn": {
          "type": "string"
        }
      },
      "required": ["kode", "navn"],
      "additionalProperties": false
    },
    "personIdentifikator": {
      "description": "Fødselsnummer (inkl. Tenor), DNummer (inkl Tenor) eller SSP nummer som alle validerer til Modulus 11",
      "type": "object",
      "properties": {
        "idType": { "$ref": "#/definitions/personIdType" },
        "verdi": {
          "type": "string",
          "description": "Se skatteetaten. Kan være vanlig med 6 sifret fødselsdato og fiktivt (Tenor) fødselsnummer med +80 på måned slik at noen født 10.01.1990 begynner fiktivt nummer med 108190",
          "pattern": "^[0-7][0-9][012389][0-9]+$",
          "minLength": 11,
          "maxLength": 11
        }
      },
      "required": ["idType", "verdi"],
      "additionalProperties": false
    },
    "personIdType": {
      "type": "string",
      "description": "Person ID typer, alle valideres med Modulus 11",
      "enum": ["FOEDSELSNUMMER", "DNUMMER", "SSPNUMMER"]
    },
    "kjoenn": {
      "description": "Samme enum som folkeregisteret",
      "enum": ["KVINNE", "MANN"],
      "type": "string"
    },
    "lengde": {
      "properties": {
        "antallAar": { "$ref": "#/definitions/aar" },
        "antallMaaneder": { "$ref": "#/definitions/maaneder" },
        "antallDager": { "$ref": "#/definitions/dager" }
      },
      "type": "object",
      "additionalProperties": false
    },
    "aar": {
      "type": "integer",
      "minimum": 1,
      "maximum": 21
    },
    "maaneder": {
      "type": "integer",
      "minimum": 1,
      "maximum": 99
    },
    "dager": {
      "type": "integer",
      "minimum": 1,
      "maximum": 999
    },
    "internId": {
      "type": "string",
      "description": "id, unik innenfor melding",
      "maxLength": 40,
      "minLength": 1
    },
    "organisasjonsnummer": {
      "type": "string",
      "description": "Norsk organisasjonsnummer fra BRREG. Referanse til politistrikt, domstol, fengsel. https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/",
      "pattern": "^[0-9]+$",
      "minLength": 9,
      "maxLength": 9
    },
    "kodeverk": {
      "properties": {
        "kode": {
          "type": "string"
        },
        "navn": {
          "type": "string"
        }
      },
      "type": "object",
      "required": ["kode"],
      "additionalProperties": false
    },
    "straffesaksnummer": {
      "type": "string",
      "description": "Som regel et løpenummer, men kan i fremtiden også inneholde bokstaver",
      "minLength": 3,
      "maxLength": 30
    },
    "epost": {
      "type": "string",
      "format": "email"
    },
    "telefonnummer": {
      "type": "string",
      "description": "Ett telefonnummer, norsk eller utenlands, med eller uten land prefix. Tillater +før landkode, - tegn, space og paranteser.",
      "pattern": "^\\+?[0-9 ()-]*$",
      "maxLength": 30,
      "minLength": 3
    },
    "datoTid": {
      "type": "string",
      "format": "date-time"
    },
    "dato": {
      "type": "string",
      "format": "date"
    },
    "GUID": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== domstolene/esas-kontrakt/kontrakter/kjennelseBeslutning/kjennelseBeslutning/eksempelfiler/kjennelse_tapAvFoererett.json
{
  "pakkeId": "734F011E-4758-4145-B299-8B2072AD06A0",
  "forsendelse": {
    "meldingsId": "2CB6929E-DE3F-49A4-8AE3-9625640DF0CC",
    "sendtTid": "2025-04-08T15:35:00+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "826726342",
        "navn": "Buskerud tingrett"
      },
      "person": {
        "etternavn": "Saksbehandler",
        "fornavn": "Litt",
        "tittel": "Saksbehandler"
      }
    },
    "mottaker": {
      "organisasjon": {
        "organisasjonsnummer": "983997953",
        "navn": "Innlandet politidistrikt"
      }
    }
  },
  "aktoerer": {
    "dommer": {
      "etternavn": "Dommersen",
      "fornavn": "Lars",
      "tittel": "Dommerfullmeltig"
    },
    "saksbehandler": {
      "etternavn": "Saksbehandler",
      "fornavn": "Litt",
      "tittel": "Saksbehandler"
    }
  },
  "dokumenter": [
    {
      "internId": "04CB1930-107B-4419-BB28-40038D8847E2",
      "forsendelse": {
        "mimeType": "application/pdf",
        "sjekksum": "1a2eced0-5792-4431-ae5c-ba0942c7e7cc",
        "uri": "9c3eced0-5792-4431-ae5c-ba0942c7e7cc"
      },
      "overskrift": "Kjennelse - Tap av f√∏rerett",
      "skrevetDato": "2025-04-08",
      "kategori": {
        "kode": "KJENNELSE"
      }
    }
  ],
  "saksInformasjon": {
    "saksnummer": "55-000132ENE-TBUS/TDRA",
    "straffesaksnummer": "16000820",
    "avgjoerelse": {
      "avgjoerelseId": "EB6432F3-F117-45A5-A4E6-F7860FF16A34",
      "avsagtDato": "2025-04-08",
      "kravId": "D16AA05B-1530-4B51-A2B7-C86DE623FC9F",
      "opprinneligKravId": "D16AA05B-1530-4B51-A2B7-C86DE623FC9F",
      "avgjoerelsePrPerson": [
        {
          "personForetak": {
            "person": {
              "internId": "948ca60c-6c7f-437d-a6a3-585cb8534280",
              "identitetsnummer": {
                "idType": "FOEDSELSNUMMER",
                "verdi": "19077046529"
              },
              "tilleggsId": [],
              "fornavn": "Masse",
              "etternavn": "Kiwi",
              "kjoenn": "MANN",
              "foedselsdato": "1970-07-19",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }
              ],
              "oppnevntForsvarer": {
                "identitetsnummer": {
                  "verdi": "22830699035",
                  "idType": "FOEDSELSNUMMER"
                },
                "fornavn": "Ultrafiolett",
                "etternavn": "Drage",
                "tittel": "Advokat",
                "kontakt": {
                  "epost": "udrage@almisse.com",
                  "telefonnummer": "22112211"
                },
                "praksis": {
                  "navn": "AKADEMISK AKADEMISK KATT ALMISSE",
                  "organisasjonsnummer": "311032348"
                }
              }
            }
          },
          "kategori": "REAKSJON",
          "typeAvgjoerelse": "KJENNELSE",
          "reaksjoner": {
            "tapAvFoererett": {
              "dato": "2025-06-08"
            }
          },
          "erklaering": {
            "erklaeringSiktede": {
              "erklaert": "VEDTATT",
              "meddeltIRettsmoete": true
            },
            "erklaeringPaatale": {
              "erklaert": "VEDTATT",
              "meddeltIRettsmoete": true
            }
          }
        }
      ]
    }
  }
}

=== domstolene/esas-kontrakt/kontrakter/kjennelseBeslutning/kjennelseBeslutning/eksempelfiler/kjennelse_tapAvFoererett_korrigering.json
{
  "pakkeId": "259A4827-E59C-4829-B5C1-D09CBC8C7989",
  "forsendelse": {
    "meldingsId": "5A933AE6-BB8A-401B-A9D8-A50FD21F396B",
    "sendtTid": "2025-04-09T16:35:00+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "826726342",
        "navn": "Buskerud tingrett"
      },
      "person": {
        "etternavn": "Saksbehandler",
        "fornavn": "Litt",
        "tittel": "Saksbehandler"
      }
    },
    "mottaker": {
      "organisasjon": {
        "organisasjonsnummer": "983997953",
        "navn": "Innlandet politidistrikt"
      }
    }
  },
  "aktoerer": {
    "dommer": {
      "etternavn": "Dommersen",
      "fornavn": "Lars",
      "tittel": "Dommerfullmeltig"
    },
    "saksbehandler": {
      "etternavn": "Saksbehandler",
      "fornavn": "Litt",
      "tittel": "Saksbehandler"
    }
  },
  "dokumenter": [
    {
      "internId": "9c3eced0-5792-4431-ae5c-ba0942c7e7cc",
      "forsendelse": {
        "mimeType": "application/pdf",
        "sjekksum": "1a2eced0-5792-4431-ae5c-ba0942c7e7cc",
        "uri": "9c3eced0-5792-4431-ae5c-ba0942c7e7cc"
      },
      "overskrift": "Kjennelse - Tap av førerett",
      "skrevetDato": "2025-04-09",
      "kategori": {
        "kode": "KJENNELSE"
      }
    }
  ],
  "saksInformasjon": {
    "saksnummer": "55-000132ENE-TBUS/TDRA",
    "straffesaksnummer": "16000820",
    "avgjoerelse": {
      "avgjoerelseId": "EB6432F3-F117-45A5-A4E6-F7860FF16A34",
      "avsagtDato": "2025-04-09",
      "kravId": "D16AA05B-1530-4B51-A2B7-C86DE623FC9F",
      "opprinneligKravId": "D16AA05B-1530-4B51-A2B7-C86DE623FC9F",
      "avgjoerelsePrPerson": [
        {
          "personForetak": {
            "person": {
              "internId": "948ca60c-6c7f-437d-a6a3-585cb8534280",
              "identitetsnummer": {
                "idType": "FOEDSELSNUMMER",
                "verdi": "19077046529"
              },
              "tilleggsId": [],
              "fornavn": "Masse",
              "etternavn": "Kiwi",
              "kjoenn": "MANN",
              "foedselsdato": "1970-07-19",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }
              ],
              "oppnevntForsvarer": {
                "identitetsnummer": {
                  "verdi": "22830699035",
                  "idType": "FOEDSELSNUMMER"
                },
                "fornavn": "Ultrafiolett",
                "etternavn": "Drage",
                "tittel": "Advokat",
                "kontakt": {
                  "epost": "udrage@almisse.com",
                  "telefonnummer": "22112211"
                },
                "praksis": {
                  "navn": "AKADEMISK AKADEMISK KATT ALMISSE",
                  "organisasjonsnummer": "311032348"
                }
              }
            }
          },
          "kategori": "REAKSJON",
          "typeAvgjoerelse": "KJENNELSE",
          "beskrivelse": "Korrigert kjennelse - endret fra dato til varighet på tapet",
          "reaksjoner": {
            "tapAvFoererett": {
              "varighet": {
                "antallMaaneder": 6
              }
            }
          },
          "erklaering": {
            "erklaeringSiktede": {
              "erklaert": "VEDTATT",
              "meddeltIRettsmoete": true,
              "meddeltDato": "2025-04-09"
            },
            "erklaeringPaatale": {
              "erklaert": "VEDTATT",
              "meddeltIRettsmoete": true
            }
          }
        }
      ]
    }
  }
}

=== domstolene/esas-kontrakt/kontrakter/kjennelseBeslutning/kjennelseBeslutning/eksempelfiler/beslutning_tilstaaelseTrukket.json
{
  "pakkeId": "C9E52A62-286F-40CA-BE74-9D0C6690BB9A",
  "forsendelse": {
    "meldingsId": "2CB6929E-DE3F-49A4-8AE3-9625640DF0CC",
    "sendtTid": "2022-07-06T16:35:00+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "826726342",
        "navn": "Buskerud tingrett"
      },
      "person": {
        "etternavn": "Saksbehandler",
        "fornavn": "Litt",
        "tittel": "Saksbehandler"
      }
    },
    "mottaker": {
      "organisasjon": {
        "organisasjonsnummer": "983997953",
        "navn": "Innlandet politidistrikt"
      }
    }
  },
  "aktoerer": {
    "dommer": {
      "etternavn": "Dommersen",
      "fornavn": "Lars",
      "tittel": "Dommerfullmeltig"
    },
    "saksbehandler": {
      "etternavn": "Saksbehandler",
      "fornavn": "Litt",
      "tittel": "Saksbehandler"
    }
  },
  "dokumenter": [
    {
      "internId": "9c3eced0-5792-4431-ae5c-ba0942c7e7cc",
      "forsendelse": {
        "mimeType": "application/pdf",
        "sjekksum": "1a2eced0-5792-4431-ae5c-ba0942c7e7cc",
        "uri": "9c3eced0-5792-4431-ae5c-ba0942c7e7cc"
      },
      "overskrift": "Avviser tilstståelsesak",
      "skrevetDato": "2022-07-06",
      "kategori": {
        "kode": "BESLUTNING"
      }
    }
  ],
  "saksInformasjon": {
    "saksnummer": "22-025462ENE-TBUS/TDRA",
    "straffesaksnummer": "15434820",
    "avgjoerelse": {
      "avgjoerelseId": "A7972F79-0A35-4EC7-90A1-81E4EFAE1ECC",
      "avsagtDato": "2022-07-05",
      "kravId": "16972F79-0A35-4EC7-90A1-81E4EFAE1ECC",
      "opprinneligKravId": "16972F79-0A35-4EC7-90A1-81E4EFAE1ECC",
      "avgjoerelsePrPerson": [
        {
          "personForetak": {
            "person": {
              "internId": "948ca60c-6c7f-437d-a6a3-585cb8534280",
              "identitetsnummer": {
                "idType": "FOEDSELSNUMMER",
                "verdi": "19077046529"
              },
              "tilleggsId": [],
              "fornavn": "Masse",
              "etternavn": "Kiwi",
              "kjoenn": "MANN",
              "foedselsdato": "1970-07-19",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }
              ]
            }
          },
          "kategori": "SAKEN_AVVIST",
          "typeAvgjoerelse": "BESLUTNING_INGEN_ANKE",
          "beskrivelse": "Siktede trakk tilståelsen så denne saken blir ikke kjørt som en tilståelsesak"
        }
      ]
    }
  }
}
